/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package org.anasoid.jmeter.as.code.core;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

public class MessageUtilsTest {
  @Test
  public void testGetMessage() {
    assertEquals("Hello      World!", MessageUtils.getMessage());
  }
}
