/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package org.anasoid.jmeter.as.code.plugin;

class MessageUtils { // NOPMD
  public static String getMessage() {
    return "Hello      World!";
  }
}
