# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Audit

on: [ push, pull_request ]

jobs:
  audit:

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu'

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.gradle/dependency-check-data
          key: ${{ runner.os }}-gradle-audit-v5-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-audit-v5



      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: dependencyCheck
        run: ./gradlew --console=verbose dependencyCheckAggregate


      - name: Publish artifact Test Report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: reports
          path: '**/build/reports/**'
