# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Audit

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.gradle/dependency-check-data
          key: ${{ runner.os }}-gradle-V1-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-V1

      - name: Cache Sonar
        uses: actions/cache@v2
        with:
          path: |
            ~/.sonar
          key: ${{ runner.os }}-sonar-V1-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-sonar-V1


      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: dependencyCheck
        run: ./gradlew dependencyCheckAggregate

      - name: Sonar check
        run: ./gradlew  --stacktrace  sonarqube -Dsonar.organization=anasoid-org -Dsonar.projectKey=anasoid_jmeter-as-code  -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


      - name: Publish artifact Test Report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: reports
          path: '**/build/reports/**'
