# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Audit

on:
  workflow_dispatch:

jobs:
  audit:

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Cache Gradle Wrapper
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-v1-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
          key: ${{ runner.os }}-gradle-audit-v8-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('gradle.properties') }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Cache Gradle Audit
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/dependency-check-data
          key: ${{ runner.os }}-gradle-audit-data-v8-${{ hashFiles('build.gradle') }}


      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: dependencyCheck
        run: ./gradlew  --stacktrace --console=verbose dependencyCheckAggregate


      - name: Publish artifact Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: reports
          path: '**/build/reports/**'
