

# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle


name: publish

on:
  workflow_dispatch:
    inputs:
      comment:
        description: 'comment'
        required: true
        default: 'TODO'
  release:
    types: [created ]

jobs:
  publish:

    runs-on: ubuntu-20.04
    env:
      MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}
      ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}

    steps:



      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: git status
        run: git status

      - name: git tag
        run: git tag

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu'


      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-publish-v5-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-publish-v5




      - name: printenv
        run: printenv

      - name: Java version
        run: java -version

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew --stacktrace --console=verbose build

      - name: Publish core
        run: ./gradlew --stacktrace --console=verbose jmc-core:publish

      - name: Publish  jmeter-plugins
        run: ./gradlew --stacktrace --console=verbose jmc-jmeter-plugins:publish

      - name: Publish  jmc-plugin
        run: ./gradlew --stacktrace --console=verbose jmc-plugin:publish

      - name: Publish test
        run: ./gradlew --stacktrace --console=verbose jmc-test:publish

      - name: Publish artifact libs
        uses: actions/upload-artifact@v2
        with:
          name: jmc-core artifacts
          path: 'jmc-core/build/libs/**'

      - name: Publish artifact libs
        uses: actions/upload-artifact@v2
        with:
          name: jmc-jmeter-plugins artifacts
          path: 'jmc-jmeter-plugins/build/libs/**'

      - name: Publish artifact libs
        uses: actions/upload-artifact@v2
        with:
          name: jmc-test artifacts
          path: 'jmc-test/build/libs/**'


