

# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle


name: publish

on:
  workflow_dispatch:
    inputs:
      comment:
        description: 'comment'
        required: true


jobs:
  publish:

    runs-on: ubuntu-20.04
    env:
      JMETER_HOME: /home/runner/.jmeter/jmeter
      JMETER_FILE: apache-jmeter-5.4.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11


      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-publish-V1-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-publish-V1



      - name: Cache Jmeter
        uses: actions/cache@v2
        with:
          path: |
            ~/.jmeter
          key: jmeter2-$JMETER_FILE

      - name: printenv
        run: printenv

      - name: Java version
        run: java -version

      - name: chmod  download-jmeter
        run: chmod +x ~/work/jmeter-as-code/jmeter-as-code/.github/scripts/download-jmeter.sh

      - name: Download Jmeter
        run: ~/work/jmeter-as-code/jmeter-as-code/.github/scripts/download-jmeter.sh

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew --stacktrace --console=verbose build

      - name: Publish core
        run: ./gradlew --stacktrace --console=verbose jmc-core:publish
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}

      - name: Publish artifact libs
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: '**/build/libs/**'



